### ISSUE TITLE
How to send prompt as System?

### ISSUE THREAD

**Issue by MZRCode** [EvanZhouDev/gemini-ai#21]
I want to give the user's name as system to inform **AI** but it gives me the warning "**Please use a valid role: user, model.**". So how can i send a **prompt as system**?

![image](https://github.com/EvanZhouDev/gemini-ai/assets/87870017/5cf8cafc-1ab2-4673-bb8a-def8ff055511)
![image](https://github.com/EvanZhouDev/gemini-ai/assets/87870017/11daaa58-ea1c-4a05-aeb7-3083b78541c9)

**Comment by MZRCode** [comment]
I tried it in 2 different ways but it couldn't say my name in these 2 ways.

![image](https://github.com/EvanZhouDev/gemini-ai/assets/87870017/1fc6de59-5fe7-4ef8-8c00-2383e06acbe5)
![image](https://github.com/EvanZhouDev/gemini-ai/assets/87870017/b4c7622a-562d-4f7c-b078-4cbc00d78a0c)

**Comment by EvanZhouDev** [comment]
Try something like "Respond like Shakespeare". System Instructions should be injecting the text correctly as a `system` role, but perhaps Gemini isn't processing it correctly.

**Comment by MZRCode** [comment]
> Try something like "Respond like Shakespeare". System Instructions should be injecting the text correctly as a `system` role, but perhaps Gemini isn't processing it correctly.

Unfortunately, that didn't work either.

Looking at **Google AI**'s **Gemini** documentation, i see that **Message** is defined as an **Object**, but you have **Message** defined as a **String**. So is **Message** defined as an **Object** or a **String**?
![image](https://github.com/EvanZhouDev/gemini-ai/assets/87870017/53ae452d-f5be-417f-b2be-b747b4584aec)
![image](https://github.com/EvanZhouDev/gemini-ai/assets/87870017/2e55b3bd-2538-4927-8989-157b24a55cb7)
![image](https://github.com/EvanZhouDev/gemini-ai/assets/87870017/8b4691a4-152c-46a3-a3e5-eee8f199e607)
![image](https://github.com/EvanZhouDev/gemini-ai/assets/87870017/0f8b0614-6ea5-4e24-93d1-206aca0d0000)
![image](https://github.com/EvanZhouDev/gemini-ai/assets/87870017/775770c3-7818-467c-b9dc-4bda72e60515)
_Document i Reviewed:_ [_**Send chat prompt requests (Gemini)**_](https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/send-chat-prompts-gemini#nodejs)

**Comment by EvanZhouDev** [comment]
Ah, it was an issue with the Chat object. It would be nice if you can specify your environment/what parts of a project you are using next time, or at least provide the code in text as it is much harder to sample pieces of information from screenshots 😅.

As for the types, Gemini AI strives to make interaction with the Gemini API as simple as possible. Though Google requires an entire Message object for System Instructions, the only reasonable thing to put there is text (You may notice even Google AI Studio only allows text in system prompts). Thus, Gemini AI will automatically construct the message object while you only have to provide it as a string.

Anywho, this bug has been fixed in v2.2.1, which should be now available on NPM.

Thank you for your contribution!

As a sidenote, providing your name in System Instructions and then directly asking for it makes Gemini refuse to answer, but if you just say "Hello", Gemini will respond with something along the lines of "Hello [Your Name]", so it does in fact work! It seems like some form of weird security measure is in place.
